---
version: 0.2

phases:
  pre_build:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install ${terraform_version}
  build:
    commands: |
      cd $${WORKING_DIR}
      grep -ril --include="*.tf" "git::https://github.com/BizGive"|grep -v .terraform| while read file
      do
        echo "file : $file"
        sed -i "s;github.com/BizGive;$GITHUB_TOKEN@github.com/BizGive;g" $file
      done
      terraform init -backend-config=$${BACKEND_CONFIG_FILE}
      [ "$WORKSPACE" != "" ] && terraform workspace select -or-create $${WORKSPACE}
      terraform apply tfplan
