---
version: 0.2
env:
  secrets-manager:
    GITHUB_TOKEN: $${GITHUB_SECRET}
phases:
  pre_build:
    commands:
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum -y install ${terraform_version}
  build:
    commands: |
      echo "WORKING_DIR : $${WORKING_DIR}"
      cd $${WORKING_DIR}
      ls -lrt
      grep -ril --include="*.tf" "git::https://github.com/BizGive"|grep -v .terraform| while read file
      do
        echo "file : $file"
        sed -i "s;github.com/BizGive;$GITHUB_TOKEN@github.com/BizGive;g" $file
      done
      terraform init -backend-config=$${BACKEND_CONFIG_FILE}
      [ "$WORKSPACE" != "" ] && terraform workspace select -or-create $${WORKSPACE}
      terraform plan -out tfplan --var-file=$${TF_VAR_FILE}
artifacts:
  files:
    - '**/*'
  name: TerraformPlan
